// origin-server.mjs
//
// A tiny static + API server standing in for a realm's "origin web server".
// It serves the production MF artifacts in dist/ AND acts as the origin's
// certificate issuer for realm attestation:
//
//   GET  /issuer.jwk     → the issuer's PUBLIC key (P-256 JWK), a trust anchor
//   POST /attest {realmId} → a compact JWS (ES256) signing
//                            { realmId, role, origin, iat, exp }
//
// The realm-id is generated by the host and passed in by the realm; this server
// only vouches for the ROLE of realms it serves. One issuer keypair is generated
// per process (per origin), so each origin is its own mini-CA.
//
// Usage:
//   node scripts/origin-server.mjs --dist apps/catalog/dist --port 4001 \
//        --role catalog --origin http://localhost:4001
//
// No dependencies — Node http + webcrypto only.

import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { join, normalize, extname } from "node:path";
import { webcrypto as crypto } from "node:crypto";

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------
function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const DIST = arg("dist", "dist");
const PORT = Number(arg("port", "4001"));
const ROLE = arg("role", "catalog");
const ORIGIN = arg("origin", `http://localhost:${PORT}`);
const CERT_TTL_SECONDS = 3600; // generous for a demo session

const CONTENT_TYPES = {
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".map": "application/json; charset=utf-8",
};

const b64url = (buf) => Buffer.from(buf).toString("base64url");

// ---------------------------------------------------------------------------
// Issuer key (one per origin process)
// ---------------------------------------------------------------------------
const issuerKey = await crypto.subtle.generateKey(
  { name: "ECDSA", namedCurve: "P-256" },
  true,
  ["sign", "verify"],
);
const issuerPublicJwk = await crypto.subtle.exportKey("jwk", issuerKey.publicKey);

async function signCertificate(realmId) {
  const header = { alg: "ES256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    realmId,
    role: ROLE,
    origin: ORIGIN,
    iat: now,
    exp: now + CERT_TTL_SECONDS,
  };
  const signingInput = `${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(payload))}`;
  const signature = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    issuerKey.privateKey,
    new TextEncoder().encode(signingInput),
  );
  // WebCrypto returns raw r||s for ECDSA — exactly the JWS ES256 format.
  return `${signingInput}.${b64url(new Uint8Array(signature))}`;
}

// ---------------------------------------------------------------------------
// HTTP
// ---------------------------------------------------------------------------
function cors(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "content-type");
}

function readBody(req) {
  return new Promise((resolve) => {
    let data = "";
    req.on("data", (c) => (data += c));
    req.on("end", () => resolve(data));
  });
}

const server = createServer(async (req, res) => {
  cors(res);
  const url = new URL(req.url, ORIGIN);

  if (req.method === "OPTIONS") {
    res.writeHead(204);
    res.end();
    return;
  }

  if (req.method === "GET" && url.pathname === "/issuer.jwk") {
    res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
    res.end(JSON.stringify(issuerPublicJwk));
    return;
  }

  if (req.method === "POST" && url.pathname === "/attest") {
    try {
      const { realmId } = JSON.parse((await readBody(req)) || "{}");
      if (!realmId || typeof realmId !== "string") {
        res.writeHead(400, { "content-type": "application/json" });
        res.end(JSON.stringify({ error: "realmId required" }));
        return;
      }
      const cert = await signCertificate(realmId);
      res.writeHead(200, { "content-type": "application/json; charset=utf-8" });
      res.end(JSON.stringify({ cert }));
    } catch (err) {
      res.writeHead(400, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: String(err) }));
    }
    return;
  }

  // Static files from dist/
  if (req.method === "GET") {
    const rel = url.pathname === "/" ? "/index.html" : url.pathname;
    // Prevent path traversal: normalize and ensure it stays within DIST.
    const filePath = normalize(join(DIST, rel));
    if (!filePath.startsWith(normalize(DIST))) {
      res.writeHead(403);
      res.end("forbidden");
      return;
    }
    try {
      const body = await readFile(filePath);
      res.writeHead(200, {
        "content-type": CONTENT_TYPES[extname(filePath)] ?? "application/octet-stream",
      });
      res.end(body);
    } catch {
      res.writeHead(404);
      res.end("not found");
    }
    return;
  }

  res.writeHead(405);
  res.end("method not allowed");
});

server.listen(PORT, () => {
  console.log(`[origin:${ROLE}] serving ${DIST} + /attest on ${ORIGIN}`);
});
